#include <emu/Emulator.h>
#include <emu/CommandLine.h>
#include <emu/Control.h>
#include <emu/tls.h>
#include <emu/KeyValueStore.h>
#include <od/glue/AppInterpreter.h>
#include <od/extras/Random.h>
//#define BUILDOPT_VERBOSE
//#define BUILDOPT_DEBUG_LEVEL 5
#include <hal/log.h>
#include <hal/timing.h>
#include <hal/heap.h>
#include <hal/uart.h>
#include <hal/events.h>
#include <hal/card.h>
#include <hal/gpio.h>
#include <hal/rng.h>
#include <hal/usb.h>
#include <hal/encoder.h>
#include <hal/pwm.h>
#include <hal/adc.h>
#include <hal/fileops.h>
#include <hal/modulation.h>
#include <hal/audio.h>
#include <hal/channels.h>
#include <hal/ops.h>
#include <hal/pump.h>
#include <od/config.h>
#include <limits.h>
#include <iostream>
#include <fstream>
#include <cstdarg>
#include <cctype>
#include <cstring>

extern "C"
{
#include "lua.h"
#include "lauxlib.h"
  // Generated by SWIG from emu/emu.cpp.swig.
  int luaopen_emu(lua_State *L);
  // Emulator-side deterministic RNG (emu/hal/rng.c). Not in hal/rng.h so the
  // firmware header stays untouched.
  void Rng_seed(uint32_t seed);
}

using namespace od;

namespace emu
{

  // Registers the `emu` SWIG module on the app interpreter's Lua state. L is a
  // protected Interpreter member, reachable from this subclass. Used only in
  // the emulator; the firmware never registers it.
  struct EmuInterpreter : public od::AppInterpreter
  {
    void registerEmuModule()
    {
      luaL_requiref(L, "emu", luaopen_emu, 1);
      lua_pop(L, 1);
    }
  };

  // Control-channel reply. Prefixed with '@' so a harness can filter our
  // replies from the firmware's stdout logging (emu/hal/log.c writes logs
  // unprefixed to stdout). Documented in planning/headless-emu-plan.md §2.
  static void ctlReply(const char *fmt, ...)
  {
    char buf[512];
    va_list a;
    va_start(a, fmt);
    vsnprintf(buf, sizeof(buf), fmt, a);
    va_end(a);
    printf("@%s\n", buf);
    fflush(stdout);
  }

  Emulator::Emulator()
  {
  }

  static int switchState(uint32_t idA, uint32_t idB)
  {
    if (Gpio_read(idA))
      return 1;
    else if (Gpio_read(idB))
      return 3;
    else
      return 2;
  }

  static void switchDown(uint32_t idA, uint32_t idB)
  {
    if (Gpio_read(idA))
      Gpio_write(idA, false);
    else if (Gpio_read(idB))
      return;
    else
      Gpio_write(idB, true);
  }

  static void switchUp(uint32_t idA, uint32_t idB)
  {
    if (Gpio_read(idA))
      return;
    else if (Gpio_read(idB))
      Gpio_write(idB, false);
    else
      Gpio_write(idA, true);
  }

  void Emulator::handleKeyUp(SDL_Keysym keysym)
  {
    std::string name = SDL_GetKeyName(keysym.sym);
    if (name == storageToggleFocusKey)
    {
      storageToggleFocused = false;
    }
    else if (name == modeToggleFocusKey)
    {
      modeToggleFocused = false;
    }
    else if (name == zoomInKey)
    {
      if (window)
        window->setScale(window->scale + 0.05f);
    }
    else if (name == zoomOutKey)
    {
      if (window)
        window->setScale(window->scale - 0.05f);
    }
    else
    {
      auto i = keyGpioMap.find(name);
      if (i != keyGpioMap.end())
      {
        uint id = (*i).second;
        Gpio_write(id, true);
      }
    }
  }

  void Emulator::handleKeyDown(SDL_Keysym keysym)
  {
    std::string name = SDL_GetKeyName(keysym.sym);
    if (name == storageToggleFocusKey)
    {
      storageToggleFocused = true;
    }
    else if (name == modeToggleFocusKey)
    {
      modeToggleFocused = true;
    }
    else if (name == quitKey && (keysym.mod & KMOD_CTRL))
    {
      quit = true;
    }
    else if (keysym.scancode == SDL_SCANCODE_UP && storageToggleFocused)
    {
      switchUp(TOGGLE_STORAGE_A, TOGGLE_STORAGE_B);
    }
    else if (keysym.scancode == SDL_SCANCODE_UP && modeToggleFocused)
    {
      switchUp(TOGGLE_MODE_A, TOGGLE_MODE_B);
    }
    else if (keysym.scancode == SDL_SCANCODE_DOWN && storageToggleFocused)
    {
      switchDown(TOGGLE_STORAGE_A, TOGGLE_STORAGE_B);
    }
    else if (keysym.scancode == SDL_SCANCODE_DOWN && modeToggleFocused)
    {
      switchDown(TOGGLE_MODE_A, TOGGLE_MODE_B);
    }
    else if (keysym.scancode == SDL_SCANCODE_LEFT)
    {
      encoderValue -= leftRightToKnobFactor * ENCODER_SPEED;
      if (window)
        window->knob.rotate(-KNOB_SPEED);
    }
    else if (keysym.scancode == SDL_SCANCODE_RIGHT)
    {
      encoderValue += leftRightToKnobFactor * ENCODER_SPEED;
      if (window)
        window->knob.rotate(KNOB_SPEED);
    }
    else if (keysym.scancode == SDL_SCANCODE_UP)
    {
      encoderValue += upDownToKnobFactor * ENCODER_SPEED;
      if (window)
        window->knob.rotate(-KNOB_SPEED);
    }
    else if (keysym.scancode == SDL_SCANCODE_DOWN)
    {
      encoderValue -= upDownToKnobFactor * ENCODER_SPEED;
      if (window)
        window->knob.rotate(KNOB_SPEED);
    }
    else
    {
      auto i = keyGpioMap.find(name);
      if (i != keyGpioMap.end())
      {
        uint id = (*i).second;
        Gpio_write(id, false);
      }
    }
  }

  static bool hit(int x, int y, SDL_Rect &rect)
  {
    return x > rect.x && x < rect.x + rect.w && y > rect.y && y < rect.y + rect.h;
  }

  static void handleSwitchHit(uint32_t idA, uint32_t idB, float p)
  {
    int state = switchState(idA, idB);
    if (p < 0.333f)
    {
      if (state == 2)
      {
        switchUp(idA, idB);
      }
      else if (state == 3)
      {
        switchUp(idA, idB);
        switchUp(idA, idB);
      }
    }
    else if (p < 0.667f)
    {
      if (state == 1)
      {
        switchDown(idA, idB);
      }
      else if (state == 3)
      {
        switchUp(idA, idB);
      }
    }
    else
    {
      if (state == 2)
      {
        switchDown(idA, idB);
      }
      else if (state == 1)
      {
        switchDown(idA, idB);
        switchDown(idA, idB);
      }
    }
  }

  void Emulator::handleMouseButton(SDL_MouseButtonEvent &e)
  {
    for (auto &kv : buttonHitMap)
    {
      uint32_t id = kv.first;
      SDL_Rect &rect = kv.second;
      if (hit(e.x, e.y, rect))
      {
        // hit!
        Gpio_write(id, e.state == SDL_RELEASED);
        return;
      }
    }

    if (e.state == SDL_RELEASED)
    {
      SDL_Rect storage{.x = T_STORAGE_X, .y = T_STORAGE_Y, .w = TOGGLE_W, .h = TOGGLE_H};
      if (hit(e.x, e.y, storage))
      {
        float p = (e.y - T_STORAGE_Y) / (float)TOGGLE_H;
        handleSwitchHit(TOGGLE_STORAGE_A, TOGGLE_STORAGE_B, p);
        return;
      }

      SDL_Rect mode{.x = T_MODE_X, .y = T_MODE_Y, .w = TOGGLE_W, .h = TOGGLE_H};
      if (hit(e.x, e.y, mode))
      {
        float p = (e.y - T_MODE_Y) / (float)TOGGLE_H;
        handleSwitchHit(TOGGLE_MODE_A, TOGGLE_MODE_B, p);
        return;
      }
    }
  }

  void Emulator::loop()
  {
    int delay = 0;
    quit = false;
    while (!quit)
    {
      tick_t start = wallclock();
      SDL_Event e;
      Pump_resetThrottle();
      //SDL_WaitEventTimeout(0, delay);
      if (delay > 0)
      {
        SDL_Delay(delay);
      }
      while (SDL_PollEvent(&e))
      {
        if (e.type == customEventType)
        {
        }
        else
        {
          switch (e.type)
          {
          case SDL_QUIT:
            quit = true;
            break;
          case SDL_KEYDOWN:
            logDebug(2, "Key Down: [%s]", SDL_GetKeyName(e.key.keysym.sym));
            handleKeyDown(e.key.keysym);
            break;
          case SDL_KEYUP:
            logDebug(2, "Key Up: [%s]", SDL_GetKeyName(e.key.keysym.sym));
            handleKeyUp(e.key.keysym);
            break;
          case SDL_MOUSEBUTTONDOWN:
          case SDL_MOUSEBUTTONUP:
            handleMouseButton(e.button);
            break;
          case SDL_MOUSEWHEEL:
            encoderValue += mouseWheelToKnobFactor * e.wheel.y * KNOB_SPEED;
            if (window)
              window->knob.rotate(e.wheel.y * KNOB_SPEED);
            break;
          case SDL_WINDOWEVENT:
            if (e.window.event == SDL_WINDOWEVENT_RESIZED)
            {
              if (window)
                window->onResized(e.window.data1, e.window.data2);
              logDebug(2, "Resize: %d x %d", e.window.data1, e.window.data2);
            }
            break;
          default:
            break;
          }
        }
      }

      // Read control commands into the pending queue. Dispatch happens in
      // serviceControl(), strictly in order, gated by wait/frames/stable/press.
      if (useControlChannel)
      {
        std::vector<std::string> lines;
        controlChannel().poll(lines);
        for (auto &l : lines)
        {
          mPending.push(l);
        }
      }

      // Recycle rendered buffers back to the ready queue. This MUST keep
      // flowing headless (window == 0) or the UI thread starves waiting for a
      // free buffer. onFrameRendered() counts frames and feeds the stable gate.
      DisplayBuffer *buffer;
      while (renderQ.pop(&buffer))
      {
        if (window)
          window->update(buffer->main, buffer->sub);
        onFrameRendered(buffer);
        readyQ.push(buffer);
      }
      Events_push(EVENT_DISPLAY_READY);

      serviceControl();

      double elapsed = ticks2secsD(wallclock() - start);
      double target = 1.0 / 70;
      double diff = MAX(0, elapsed - target);
      delay = (int)(1000 * (target - diff));
      if (delay < 0)
      {
        delay = 0;
      }
    }
  }

  void Emulator::buildButtonNameMap()
  {
    nameButtonMap["MAIN1"] = BUTTON_MAIN1;
    nameButtonMap["MAIN2"] = BUTTON_MAIN2;
    nameButtonMap["MAIN3"] = BUTTON_MAIN3;
    nameButtonMap["MAIN4"] = BUTTON_MAIN4;
    nameButtonMap["MAIN5"] = BUTTON_MAIN5;
    nameButtonMap["MAIN6"] = BUTTON_MAIN6;
    nameButtonMap["DIAL1"] = BUTTON_DIAL1;
    nameButtonMap["DIAL2"] = BUTTON_DIAL2;
    nameButtonMap["DIAL3"] = BUTTON_DIAL3;
    nameButtonMap["SUB1"] = BUTTON_SUB1;
    nameButtonMap["SUB2"] = BUTTON_SUB2;
    nameButtonMap["SUB3"] = BUTTON_SUB3;
    nameButtonMap["ENTER"] = BUTTON_ENTER;
    nameButtonMap["UP"] = BUTTON_UP;
    nameButtonMap["SHIFT"] = BUTTON_SHIFT;
    nameButtonMap["SELECT1"] = BUTTON_SELECT1;
    nameButtonMap["SELECT2"] = BUTTON_SELECT2;
    nameButtonMap["SELECT3"] = BUTTON_SELECT3;
    nameButtonMap["SELECT4"] = BUTTON_SELECT4;
  }

  static std::string upcase(const std::string &s)
  {
    std::string out = s;
    for (char &c : out)
      c = (char)toupper((unsigned char)c);
    return out;
  }

  static void tokenize(const std::string &line, std::vector<std::string> &tok)
  {
    size_t i = 0;
    while (i < line.size())
    {
      while (i < line.size() && isspace((unsigned char)line[i]))
        i++;
      size_t j = i;
      while (j < line.size() && !isspace((unsigned char)line[j]))
        j++;
      if (j > i)
        tok.push_back(line.substr(i, j - i));
      i = j;
    }
  }

  // Returns everything after the first whitespace-delimited token, verbatim
  // (used for `lua CODE` and `cap PATH`, whose arguments may contain spaces).
  static std::string remainder(const std::string &line)
  {
    size_t i = 0;
    while (i < line.size() && isspace((unsigned char)line[i]))
      i++;
    while (i < line.size() && !isspace((unsigned char)line[i]))
      i++;
    while (i < line.size() && isspace((unsigned char)line[i]))
      i++;
    return line.substr(i);
  }

  // [stol:emu-cmd-toggles]
  bool Emulator::setSwitchPosition(uint32_t idA, uint32_t idB, const std::string &pos)
  {
    // switchState: 1 = up (A), 2 = center, 3 = down (B). switchUp moves
    // down->center->up, switchDown moves up->center->down (see statics above).
    std::string p = upcase(pos);
    if (p == "UP")
    {
      while (switchState(idA, idB) != 1)
        switchUp(idA, idB);
      return true;
    }
    else if (p == "CENTER" || p == "MIDDLE")
    {
      int s = switchState(idA, idB);
      if (s == 1)
        switchDown(idA, idB);
      else if (s == 3)
        switchUp(idA, idB);
      return true;
    }
    else if (p == "DOWN")
    {
      while (switchState(idA, idB) != 3)
        switchDown(idA, idB);
      return true;
    }
    return false;
  }

  // [stol:emu-cmd-buttons] [stol:emu-cmd-encoder] [stol:emu-capture-fb]
  void Emulator::handleControlLine(const std::string &line)
  {
    std::vector<std::string> tok;
    tokenize(line, tok);
    if (tok.empty())
      return; // blank line: no reply
    const std::string cmd = tok[0];

    if (cmd == "quit")
    {
      quit = true;
      ctlReply("ok");
    }
    else if (cmd == "down" || cmd == "up")
    {
      if (tok.size() < 2)
      {
        ctlReply("err %s needs a button name", cmd.c_str());
        return;
      }
      auto it = nameButtonMap.find(upcase(tok[1]));
      if (it == nameButtonMap.end())
      {
        ctlReply("err unknown button %s", tok[1].c_str());
        return;
      }
      // GPIO is inverted: a button DOWN writes false, UP writes true.
      Gpio_write(it->second, cmd == "up");
      ctlReply("ok");
    }
    else if (cmd == "press")
    {
      if (tok.size() < 2)
      {
        ctlReply("err press needs a button name");
        return;
      }
      auto it = nameButtonMap.find(upcase(tok[1]));
      if (it == nameButtonMap.end())
      {
        ctlReply("err unknown button %s", tok[1].c_str());
        return;
      }
      double ms = (tok.size() >= 3) ? atof(tok[2].c_str()) : 60.0;
      Gpio_write(it->second, false); // down
      mPressButton = it->second;
      mGate = ControlGate::Press;
      mGateStartTicks = ticks();
      mGateMs = ms;
      // reply deferred until the scheduled release fires in serviceControl().
    }
    else if (cmd == "turn")
    {
      if (tok.size() < 2)
      {
        ctlReply("err turn needs a delta");
        return;
      }
      // Raw detent units, matching the SDL arrow-key accumulator.
      encoderValue += atoi(tok[1].c_str());
      ctlReply("ok");
    }
    else if (cmd == "mode" || cmd == "storage")
    {
      if (tok.size() < 2)
      {
        ctlReply("err %s needs up|center|down", cmd.c_str());
        return;
      }
      uint32_t a = (cmd == "mode") ? TOGGLE_MODE_A : TOGGLE_STORAGE_A;
      uint32_t b = (cmd == "mode") ? TOGGLE_MODE_B : TOGGLE_STORAGE_B;
      if (setSwitchPosition(a, b, tok[1]))
        ctlReply("ok");
      else
        ctlReply("err bad position %s (want up|center|down)", tok[1].c_str());
    }
    else if (cmd == "wait")
    {
      if (tok.size() < 2)
      {
        ctlReply("err wait needs milliseconds");
        return;
      }
      mGate = ControlGate::Wait;
      mGateStartTicks = ticks();
      mGateMs = atof(tok[1].c_str());
    }
    else if (cmd == "frames")
    {
      if (tok.size() < 2)
      {
        ctlReply("err frames needs a count");
        return;
      }
      mGate = ControlGate::Frames;
      mGateFrameTarget = mFrameCount + atol(tok[1].c_str());
    }
    else if (cmd == "stable")
    {
      if (tok.size() < 2)
      {
        ctlReply("err stable needs a frame count");
        return;
      }
      mStableNeed = atoi(tok[1].c_str());
      if (mStableNeed < 1)
        mStableNeed = 1;
      mStableTimeout = (tok.size() >= 3) ? atol(tok[2].c_str()) : 300;
      mStableCount = 0;
      mStableHavePrev = false;
      mStableStartFrame = mFrameCount;
      mGate = ControlGate::Stable;
    }
    else if (cmd == "cap")
    {
      std::string path = remainder(line);
      if (path.empty())
      {
        ctlReply("err cap needs a path");
        return;
      }
      // Escape for embedding in a Lua double-quoted string literal.
      std::string esc;
      for (char c : path)
      {
        if (c == '\\' || c == '"')
          esc.push_back('\\');
        esc.push_back(c);
      }
      std::string code = "return app.UIThread.saveScreenShotTo(\"" + esc + "\")";
      controlChannel().enqueueLua(code.c_str());
      mGate = ControlGate::Lua; // reply arrives from the Lua drain
    }
    else if (cmd == "lua")
    {
      std::string code = remainder(line);
      controlChannel().enqueueLua(code.c_str());
      mGate = ControlGate::Lua; // reply arrives from the Lua drain
    }
    else
    {
      ctlReply("err unknown command %s", cmd.c_str());
    }
  }

  void Emulator::onFrameRendered(DisplayBuffer *buffer)
  {
    mFrameCount++;
    if (mGate == ControlGate::Stable)
    {
      if (mStableHavePrev &&
          memcmp(mStablePrev.main, buffer->main, sizeof(buffer->main)) == 0 &&
          memcmp(mStablePrev.sub, buffer->sub, sizeof(buffer->sub)) == 0)
      {
        mStableCount++;
      }
      else
      {
        mStableCount = 0;
      }
      memcpy(mStablePrev.main, buffer->main, sizeof(buffer->main));
      memcpy(mStablePrev.sub, buffer->sub, sizeof(buffer->sub));
      mStableHavePrev = true;
    }
  }

  // [stol:emu-cmd-stable]
  void Emulator::serviceControl()
  {
    if (!useControlChannel)
      return;

    // Forward replies pushed by the Lua thread. Each reply also closes an
    // active Lua gate, except the unsolicited 'ready' handshake line.
    std::string r;
    while (controlChannel().popReply(r))
    {
      ctlReply("%s", r.c_str());
      if (mGate == ControlGate::Lua && r != "ready")
        mGate = ControlGate::None;
    }

    switch (mGate)
    {
    case ControlGate::Wait:
      if (ticks2secsD(ticks() - mGateStartTicks) * 1000.0 >= mGateMs)
      {
        mGate = ControlGate::None;
        ctlReply("ok");
      }
      break;
    case ControlGate::Press:
      if (ticks2secsD(ticks() - mGateStartTicks) * 1000.0 >= mGateMs)
      {
        Gpio_write(mPressButton, true); // release
        mGate = ControlGate::None;
        ctlReply("ok");
      }
      break;
    case ControlGate::Frames:
      if (mFrameCount >= mGateFrameTarget)
      {
        mGate = ControlGate::None;
        ctlReply("ok");
      }
      break;
    case ControlGate::Stable:
      if (mStableCount >= mStableNeed)
      {
        mGate = ControlGate::None;
        ctlReply("ok %ld", mFrameCount);
      }
      else if ((mFrameCount - mStableStartFrame) >= mStableTimeout)
      {
        mGate = ControlGate::None;
        ctlReply("err timeout");
      }
      break;
    case ControlGate::Lua:
    case ControlGate::None:
      break;
    }

    // Dispatch the next command only when no gate is pending.
    if (mGate == ControlGate::None && !mPending.empty())
    {
      std::string line = mPending.front();
      mPending.pop();
      handleControlLine(line);
    }

    // Headless with no more input and nothing pending: exit cleanly so a
    // script that omits `quit` still terminates.
    if (headless && mGate == ControlGate::None && mPending.empty() &&
        controlChannel().atEof())
    {
      quit = true;
    }
  }

  DisplayBuffer *Emulator::getDisplayBuffer()
  {
    DisplayBuffer *buffer = 0;
    readyQ.pop(&buffer);
    return buffer;
  }

  void Emulator::putDisplayBuffer(DisplayBuffer *buffer)
  {
    renderQ.push(buffer);
    SDL_Event e;
    SDL_zero(e);
    e.type = customEventType;
    SDL_PushEvent(&e);
  }

  int Emulator::getEncoderValue()
  {
    return encoderValue + INT32_MAX / 2;
  }

  bool Emulator::isRearCardPresent()
  {
    return rearCardPresent;
  }

  bool Emulator::isFrontCardPresent()
  {
    return frontCardPresent;
  }

  // Grrr. The realpath function doesn't handle the tilde.
  static char *realpathEx(const char *path, char *buff)
  {
    char *home;
    if (*path == '~' && (home = getenv("HOME")))
    {
      char s[PATH_MAX];
      return realpath(strcat(strcpy(s, home), path + 1), buff);
    }
    else
    {
      return realpath(path, buff);
    }
  }

  bool Emulator::writeDefaultConfiguration(const std::string &filename)
  {
    std::ofstream f;
    f.open(filename);
    if (!f.is_open())
      return false;

    f << "## ER-301 Emulator Configuration\n";
    f << '\n';
    f << "## Uncomment lines below to set your own values.\n";
    f << '\n';
    f << "## Root for the Lua interpreter\n";
    f << "# XROOT ./xroot\n";
    f << '\n';
    f << "## Use this root for the rear SD card.\n";
    f << "# REAR_ROOT ~/.od/rear\n";
    f << "# REAR_PRESENT true\n";
    f << '\n';
    f << "## Use this root for the front SD card.\n";
    f << "# FRONT_ROOT ~/.od/front\n";
    f << "# FRONT_PRESENT true\n";
    f << '\n';
    f << "## Key mapping\n";
    f << '\n';
    f << "# BUTTON_MAIN1_KEY " << gpioKeyMap[BUTTON_MAIN1] << '\n';
    f << "# BUTTON_MAIN2_KEY " << gpioKeyMap[BUTTON_MAIN2] << '\n';
    f << "# BUTTON_MAIN3_KEY " << gpioKeyMap[BUTTON_MAIN3] << '\n';
    f << "# BUTTON_MAIN4_KEY " << gpioKeyMap[BUTTON_MAIN4] << '\n';
    f << "# BUTTON_MAIN5_KEY " << gpioKeyMap[BUTTON_MAIN5] << '\n';
    f << "# BUTTON_MAIN6_KEY " << gpioKeyMap[BUTTON_MAIN6] << '\n';
    f << "# BUTTON_DIAL1_KEY " << gpioKeyMap[BUTTON_DIAL1] << '\n';
    f << "# BUTTON_DIAL2_KEY " << gpioKeyMap[BUTTON_DIAL2] << '\n';
    f << "# BUTTON_DIAL3_KEY " << gpioKeyMap[BUTTON_DIAL3] << '\n';
    f << "# BUTTON_SUB1_KEY " << gpioKeyMap[BUTTON_SUB1] << '\n';
    f << "# BUTTON_SUB2_KEY " << gpioKeyMap[BUTTON_SUB2] << '\n';
    f << "# BUTTON_SUB3_KEY " << gpioKeyMap[BUTTON_SUB3] << '\n';
    f << "# BUTTON_ENTER_KEY " << gpioKeyMap[BUTTON_ENTER] << '\n';
    f << "# BUTTON_UP_KEY " << gpioKeyMap[BUTTON_UP] << '\n';
    f << "# BUTTON_SHIFT_KEY " << gpioKeyMap[BUTTON_SHIFT] << '\n';
    f << "# BUTTON_SELECT1_KEY " << gpioKeyMap[BUTTON_SELECT1] << '\n';
    f << "# BUTTON_SELECT2_KEY " << gpioKeyMap[BUTTON_SELECT2] << '\n';
    f << "# BUTTON_SELECT3_KEY " << gpioKeyMap[BUTTON_SELECT3] << '\n';
    f << "# BUTTON_SELECT4_KEY " << gpioKeyMap[BUTTON_SELECT4] << '\n';
    f << "# STORAGE_FOCUS_KEY " << storageToggleFocusKey << '\n';
    f << "# MODE_FOCUS_KEY " << modeToggleFocusKey << '\n';
    f << "# ZOOM_IN_KEY " << zoomInKey << '\n';
    f << "# ZOOM_OUT_KEY " << zoomOutKey << '\n';
    f << "# QUIT_KEY " << quitKey << '\n';
    f << '\n';
    f << "## Knob mapping\n";
    f << '\n';
    f << "##  Scale factor for mouse wheel. Negate to invert.\n";
    f << "# MOUSE_WHEEL_FACTOR " << mouseWheelToKnobFactor << "\n";
    f << '\n';
    f << "##  Scale factor for LEFT/RIGHT arrow keys. Negate to invert.\n";
    f << "# LEFT_RIGHT_ARROWS_FACTOR " << leftRightToKnobFactor << "\n";
    f << '\n';
    f << "##  Scale factor for UP/DOWN arrow keys. Negate to invert.\n";
    f << "# UP_DOWN_ARROWS_FACTOR " << upDownToKnobFactor << '\n';
    f << '\n';

    f.close();
    return true;
  }

  void Emulator::loadDefaultConfiguration()
  {
    char tmp[PATH_MAX];

    // Set default paths
    realpathEx("~/.od", tmp);
    configRoot = tmp;
    createDirectory(tmp);
    rearRoot = configRoot + "/rear";
    rearCardPresent = true;
    frontRoot = configRoot + "/front";
    frontCardPresent = true;
    sessionFilename = configRoot + "/emu.session";
    configFilename = configRoot + "/emu.config";
    realpathEx("./xroot", tmp);
    xRoot = tmp;

    // Set default key map
    mapButtonToKey(BUTTON_MAIN1, "Q");
    mapButtonToKey(BUTTON_MAIN2, "W");
    mapButtonToKey(BUTTON_MAIN3, "E");
    mapButtonToKey(BUTTON_MAIN4, "R");
    mapButtonToKey(BUTTON_MAIN5, "T");
    mapButtonToKey(BUTTON_MAIN6, "Y");
    mapButtonToKey(BUTTON_DIAL1, "A");
    mapButtonToKey(BUTTON_DIAL2, "S");
    mapButtonToKey(BUTTON_DIAL3, "D");
    mapButtonToKey(BUTTON_SUB1, "F");
    mapButtonToKey(BUTTON_SUB2, "G");
    mapButtonToKey(BUTTON_SUB3, "H");
    mapButtonToKey(BUTTON_ENTER, "V");
    mapButtonToKey(BUTTON_UP, "B");
    mapButtonToKey(BUTTON_SHIFT, "N");
    mapButtonToKey(BUTTON_SELECT1, "1");
    mapButtonToKey(BUTTON_SELECT2, "2");
    mapButtonToKey(BUTTON_SELECT3, "3");
    mapButtonToKey(BUTTON_SELECT4, "4");
    storageToggleFocusKey = "Z";
    modeToggleFocusKey = "X";
    zoomInKey = "=";
    zoomOutKey = "-";
    quitKey = "Q";

    // Set default knob mapping
    mouseWheelToKnobFactor = 0.5;
    leftRightToKnobFactor = 1;
    upDownToKnobFactor = 0.25;
  }

  bool Emulator::loadConfiguration(const std::string &filename)
  {
    KeyValueStore db;
    if (db.load(filename))
    {
      // Override default key map
      mapButtonToKey(BUTTON_MAIN1, db.get("BUTTON_MAIN1_KEY", gpioKeyMap[BUTTON_MAIN1]));
      mapButtonToKey(BUTTON_MAIN2, db.get("BUTTON_MAIN2_KEY", gpioKeyMap[BUTTON_MAIN2]));
      mapButtonToKey(BUTTON_MAIN3, db.get("BUTTON_MAIN3_KEY", gpioKeyMap[BUTTON_MAIN3]));
      mapButtonToKey(BUTTON_MAIN4, db.get("BUTTON_MAIN4_KEY", gpioKeyMap[BUTTON_MAIN4]));
      mapButtonToKey(BUTTON_MAIN5, db.get("BUTTON_MAIN5_KEY", gpioKeyMap[BUTTON_MAIN5]));
      mapButtonToKey(BUTTON_MAIN6, db.get("BUTTON_MAIN6_KEY", gpioKeyMap[BUTTON_MAIN6]));
      mapButtonToKey(BUTTON_DIAL1, db.get("BUTTON_DIAL1_KEY", gpioKeyMap[BUTTON_DIAL1]));
      mapButtonToKey(BUTTON_DIAL2, db.get("BUTTON_DIAL2_KEY", gpioKeyMap[BUTTON_DIAL2]));
      mapButtonToKey(BUTTON_DIAL3, db.get("BUTTON_DIAL3_KEY", gpioKeyMap[BUTTON_DIAL3]));
      mapButtonToKey(BUTTON_SUB1, db.get("BUTTON_SUB1_KEY", gpioKeyMap[BUTTON_SUB1]));
      mapButtonToKey(BUTTON_SUB2, db.get("BUTTON_SUB2_KEY", gpioKeyMap[BUTTON_SUB2]));
      mapButtonToKey(BUTTON_SUB3, db.get("BUTTON_SUB3_KEY", gpioKeyMap[BUTTON_SUB3]));
      mapButtonToKey(BUTTON_ENTER, db.get("BUTTON_ENTER_KEY", gpioKeyMap[BUTTON_ENTER]));
      mapButtonToKey(BUTTON_UP, db.get("BUTTON_UP_KEY", gpioKeyMap[BUTTON_UP]));
      mapButtonToKey(BUTTON_SHIFT, db.get("BUTTON_SHIFT_KEY", gpioKeyMap[BUTTON_SHIFT]));
      mapButtonToKey(BUTTON_SELECT1, db.get("BUTTON_SELECT1_KEY", gpioKeyMap[BUTTON_SELECT1]));
      mapButtonToKey(BUTTON_SELECT2, db.get("BUTTON_SELECT2_KEY", gpioKeyMap[BUTTON_SELECT2]));
      mapButtonToKey(BUTTON_SELECT3, db.get("BUTTON_SELECT3_KEY", gpioKeyMap[BUTTON_SELECT3]));
      mapButtonToKey(BUTTON_SELECT4, db.get("BUTTON_SELECT4_KEY", gpioKeyMap[BUTTON_SELECT4]));
      storageToggleFocusKey = db.get("STORAGE_FOCUS_KEY", storageToggleFocusKey);
      modeToggleFocusKey = db.get("MODE_FOCUS_KEY", modeToggleFocusKey);
      zoomInKey = db.get("ZOOM_IN_KEY", zoomInKey);
      zoomOutKey = db.get("ZOOM_OUT_KEY", zoomOutKey);
      quitKey = db.get("QUIT_KEY", quitKey);

      // Override knob settings
      mouseWheelToKnobFactor = db.getFloat("MOUSE_WHEEL_FACTOR", mouseWheelToKnobFactor);
      leftRightToKnobFactor = db.getFloat("LEFT_RIGHT_ARROWS_FACTOR", leftRightToKnobFactor);
      upDownToKnobFactor = db.getFloat("UP_DOWN_ARROWS_FACTOR", upDownToKnobFactor);

      // Override default paths
      char tmp[PATH_MAX];

      realpath(db.get("XROOT", xRoot).c_str(), tmp);
      xRoot = tmp;

      realpath(db.get("REAR_ROOT", rearRoot).c_str(), tmp);
      rearRoot = tmp;
      if (db.get("REAR_PRESENT", "true") == "false")
      {
        logWarn("Rear card configured to be NOT present.");
        rearCardPresent = false;
      }

      realpath(db.get("FRONT_ROOT", frontRoot).c_str(), tmp);
      frontRoot = tmp;
      if (db.get("FRONT_PRESENT", "true") == "false")
      {
        logWarn("Front card configured to be NOT present.");
        frontCardPresent = false;
      }

      return true;
    }
    else
    {
      return false;
    }
  }

  void Emulator::restoreState()
  {
    // Restore emulator state.
    if (pathExists(sessionFilename.c_str()))
    {
      KeyValueStore db;
      if (db.load(sessionFilename))
      {
        Gpio_write(TOGGLE_STORAGE_A, db["TOGGLE_STORAGE_A"] == "1");
        Gpio_write(TOGGLE_STORAGE_B, db["TOGGLE_STORAGE_B"] == "1");
        Gpio_write(TOGGLE_MODE_A, db["TOGGLE_MODE_A"] == "1");
        Gpio_write(TOGGLE_MODE_B, db["TOGGLE_MODE_B"] == "1");

        if (window && db.has("WINDOW_X"))
        {
          int x = db.getInteger("WINDOW_X");
          int y = db.getInteger("WINDOW_Y");
          int correction = db.getInteger("WINDOW_CORRECTION");
          window->setPosition(x, y, correction);
        }

        if (window && db.has("WINDOW_SCALE"))
        {
          float scale = db.getFloat("WINDOW_SCALE");
          if (scale > 0.0f)
          {
            window->setScale(scale);
          }
        }

        logInfo("Restored emulator state from %s.", sessionFilename.c_str());
      }
      else
      {
        logWarn("Failed to load from %s.", sessionFilename.c_str());
      }
    }
  }

  void Emulator::saveState()
  {
    KeyValueStore db;

    // Save emulator state.
    if (Gpio_read(TOGGLE_STORAGE_A))
    {
      db["TOGGLE_STORAGE_A"] = "1";
    }
    else
    {
      db["TOGGLE_STORAGE_A"] = "0";
    }

    if (Gpio_read(TOGGLE_STORAGE_B))
    {
      db["TOGGLE_STORAGE_B"] = "1";
    }
    else
    {
      db["TOGGLE_STORAGE_B"] = "0";
    }

    if (Gpio_read(TOGGLE_MODE_A))
    {
      db["TOGGLE_MODE_A"] = "1";
    }
    else
    {
      db["TOGGLE_MODE_A"] = "0";
    }

    if (Gpio_read(TOGGLE_MODE_B))
    {
      db["TOGGLE_MODE_B"] = "1";
    }
    else
    {
      db["TOGGLE_MODE_B"] = "0";
    }

    // Skip window geometry headless (window == 0); toggle state above is
    // still persisted so a subsequent windowed run restores it.
    if (window)
    {
      db.setFloat("WINDOW_SCALE", window->scale);

      int x, y;
      window->getPosition(x, y);
      db.setInteger("WINDOW_X", x);
      db.setInteger("WINDOW_Y", y);
      db.setInteger("WINDOW_CORRECTION", window->getTitleBarHeight());
    }

    if (db.save(sessionFilename))
    {
      logInfo("Saved emulator state to %s.", sessionFilename.c_str());
    }
    else
    {
      logWarn("Failed to save to %s.", sessionFilename.c_str());
    }
  }

  void Emulator::mapButtonToKey(uint32_t id, const std::string &key)
  {
    keyGpioMap[key] = id;
    gpioKeyMap[id] = key;
    if (!window)
      return;
    for (Button &b : window->buttons)
    {
      if (id == b.id)
      {
        b.key = key;
      }
    }
  }

  static int interpreterThreadStart(void *ptr)
  {
    TLS_setName("lua");
    EmuInterpreter interp;
    interp.init();
    // Register the `emu` Lua module so Application.lua can reach the control
    // bridge (emu.hasControlInput / popControlLine / pushControlReply).
    interp.registerEmuModule();
    interp.execute("package.path = '%s/?.lua;%s/?/init.lua'", globalConfig.xRoot, globalConfig.xRoot);
    interp.execute("app.EMULATION = true");
    interp.execute("app.roots = {x='%s',rear='%s',front='%s'}",
                   globalConfig.xRoot, globalConfig.rearRoot, globalConfig.frontRoot);
    interp.execute("dofile('%s/boot/logging.lua')", globalConfig.xRoot);
    interp.execute("dofile('%s/boot/start.lua')", globalConfig.xRoot);
    return 0;
  }

  int Emulator::run(int argc, char **argv)
  {
    CommandLine cmdLine(argc, argv);
    if (cmdLine.optionExists("-h") || cmdLine.optionExists("--help"))
    {
      printf("ER-301 Emulator (v" FIRMWARE_VERSION ")\n");
      printf("Usage: emu.elf [OPTIONS]\n\n");
      printf("Examples:\n");
      printf("  emu.elf              # Start emulator with default configuration file.\n");
      printf("  emu.elf -c foo.cfg   # Start emulator with 'foo.cfg'.\n");
      printf("\n");
      printf("  -h, --help         Show this help.\n");
      printf("  -c, --config FILE  Use the given configuration file.\n");
      printf("                     (Default: ~/.od/emu.config)\n");
      printf("  --headless         Run with no SDL window (dummy video driver);\n");
      printf("                     read a line-oriented control protocol on stdin.\n");
      printf("  --control PATH     Read the control protocol from FIFO PATH\n");
      printf("                     (works windowed too).\n");
      printf("  --seed N           Seed the emulator RNG deterministically.\n");
      return 0;
    }

    // [stol:emu-headless-boot]
    headless = cmdLine.optionExists("--headless");
    if (cmdLine.optionExists("--control"))
    {
      controlPath = cmdLine.getOption("--control");
    }
    useControlChannel = headless || !controlPath.empty();

    // [stol:emu-seed-flag]
    if (cmdLine.optionExists("--seed"))
    {
      Rng_seed((uint32_t)strtoul(cmdLine.getOption("--seed").c_str(), 0, 10));
    }

    // Must be set before SDL_Init so SDL never opens a display connection.
    if (headless)
    {
      setenv("SDL_VIDEODRIVER", "dummy", 1);
    }

    TLS_setName("main");
    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS | SDL_INIT_TIMER) < 0)
    {
      logFatal("SDL could not initialize! SDL_Error: %s", SDL_GetError());
    }

    customEventType = SDL_RegisterEvents(1);
    if (!headless)
    {
      window = new Window();
    }

    loadDefaultConfiguration();
    // Optionally override configuration file with cmdline.
    if (cmdLine.optionExists("-c"))
    {
      configFilename = cmdLine.getOption("-c");
    }
    if (cmdLine.optionExists("--config"))
    {
      configFilename = cmdLine.getOption("--config");
    }

    if (!pathExists(configFilename.c_str()))
    {
      logWarn("%s does not exist, creating a default one.", configFilename.c_str());
      writeDefaultConfiguration(configFilename);
    }
    else if (!loadConfiguration(configFilename))
    {
      logWarn("There was a problem loading %s.  Using default emulator configuration.", configFilename.c_str());
    }

    Heap_init();
    Timing_init();
    Uart_init();
    Card_init();
    Uart_enable();
    Log_init();

    std::string firmwareCfg = rearRoot;
    firmwareCfg += "/firmware.cfg";
    Config_init(firmwareCfg.c_str(), xRoot.c_str(), rearRoot.c_str(), frontRoot.c_str());

    Pump_init();
    Rng_init();
    Gpio_init();
    Events_init();
    USB_init();
    Encoder_init();
    Pwm_init();
    Adc_init();
    Modulation_init();
    Audio_init();
    Display_init();
    od::Random::init();

    memset(ping.main, 0, sizeof(ping.main));
    memset(pong.main, 0, sizeof(pong.main));
    memset(ping.sub, 0, sizeof(ping.sub));
    memset(pong.sub, 0, sizeof(pong.sub));

    readyQ.push(&ping);
    readyQ.push(&pong);
    Events_push(EVENT_DISPLAY_READY);

    buttonHitMap[BUTTON_MAIN1] = {.x = MB1_X, .y = MB1_Y, .w = BUTTON_W, .h = BUTTON_H};
    buttonHitMap[BUTTON_MAIN2] = {.x = MB2_X, .y = MB1_Y, .w = BUTTON_W, .h = BUTTON_H};
    buttonHitMap[BUTTON_MAIN3] = {.x = MB3_X, .y = MB1_Y, .w = BUTTON_W, .h = BUTTON_H};
    buttonHitMap[BUTTON_MAIN4] = {.x = MB4_X, .y = MB1_Y, .w = BUTTON_W, .h = BUTTON_H};
    buttonHitMap[BUTTON_MAIN5] = {.x = MB5_X, .y = MB1_Y, .w = BUTTON_W, .h = BUTTON_H};
    buttonHitMap[BUTTON_MAIN6] = {.x = MB6_X, .y = MB1_Y, .w = BUTTON_W, .h = BUTTON_H};
    buttonHitMap[BUTTON_DIAL1] = {.x = MB1_X, .y = SB1_Y, .w = BUTTON_W, .h = BUTTON_H};
    buttonHitMap[BUTTON_DIAL2] = {.x = MB2_X, .y = SB1_Y, .w = BUTTON_W, .h = BUTTON_H};
    buttonHitMap[BUTTON_DIAL3] = {.x = MB3_X, .y = SB1_Y, .w = BUTTON_W, .h = BUTTON_H};
    buttonHitMap[BUTTON_SUB1] = {.x = MB4_X, .y = SB1_Y, .w = BUTTON_W, .h = BUTTON_H};
    buttonHitMap[BUTTON_SUB2] = {.x = MB5_X, .y = SB1_Y, .w = BUTTON_W, .h = BUTTON_H};
    buttonHitMap[BUTTON_SUB3] = {.x = MB6_X, .y = SB1_Y, .w = BUTTON_W, .h = BUTTON_H};
    buttonHitMap[BUTTON_ENTER] = {.x = MB4_X, .y = HB1_Y, .w = BUTTON_W, .h = BUTTON_H};
    buttonHitMap[BUTTON_UP] = {.x = MB5_X, .y = HB1_Y, .w = BUTTON_W, .h = BUTTON_H};
    buttonHitMap[BUTTON_SHIFT] = {.x = MB6_X, .y = HB1_Y, .w = BUTTON_W, .h = BUTTON_H};
    buttonHitMap[BUTTON_SELECT1] = {.x = JB1_X, .y = JB1_Y, .w = BUTTON_W, .h = BUTTON_H};
    buttonHitMap[BUTTON_SELECT2] = {.x = JB1_X, .y = JB2_Y, .w = BUTTON_W, .h = BUTTON_H};
    buttonHitMap[BUTTON_SELECT3] = {.x = JB1_X, .y = JB3_Y, .w = BUTTON_W, .h = BUTTON_H};
    buttonHitMap[BUTTON_SELECT4] = {.x = JB1_X, .y = JB4_Y, .w = BUTTON_W, .h = BUTTON_H};

    if (headless)
    {
      // [stol:emu-headless-boot] Never touch the shared ~/.od/emu.session in
      // headless mode: restoring it bleeds toggle state (and thus the boot
      // context) across scripted runs, breaking determinism. Instead set a
      // fixed default — STORAGE=user so boots land on the home view; scripts
      // override with the `storage`/`mode` commands.
      Gpio_write(TOGGLE_STORAGE_A, true);
      Gpio_write(TOGGLE_STORAGE_B, false);
      Gpio_write(TOGGLE_MODE_A, false);
      Gpio_write(TOGGLE_MODE_B, false);
    }
    else
    {
      restoreState();
    }

    buildButtonNameMap();
    if (useControlChannel)
    {
      bool ok = controlPath.empty() ? controlChannel().openStdin()
                                    : controlChannel().openFifo(controlPath.c_str());
      if (!ok)
      {
        logError("Failed to open control channel; scripted input disabled.");
        useControlChannel = false;
      }
    }

    SDL_Thread *interpreterThread = SDL_CreateThread(interpreterThreadStart, "interp", 0);
    if (interpreterThread == 0)
    {
      logError("Failed to create Interpreter Thread.");
      goto error;
    }

    logInfo("Entering emulator loop.");
    loop();
    logInfo("Exiting emulator loop.");

    Events_push(EVENT_QUIT);
    logInfo("Waiting for interpreter to finish...");
    SDL_WaitThread(interpreterThread, 0);

    // Headless runs never persist session state (see the restore guard above).
    if (!headless)
    {
      saveState();
    }

  error:
    logInfo("Exiting...");
    delete window;
    SDL_Quit();
    return 0;
  }

} // namespace emu
